# Promote a GitOps application from one environment to the next

name: Promote application simple

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      source_env:
        description: "Source environment"
        required: true
        default: "devtest"
        type: choice
        options:
          - devtest
          - staging
          - production
      target_env:
        description: "Target environment"
        required: true
        default: "staging"
        type: choice
        options:
          - devtest
          - staging
          - production
      promote_container:
        description: "Promote image version"
        required: true
        type: boolean
        default: "true"
      promote_services:
        description: "Also promote service changes"
        required: true
        type: boolean
      messsage:
        description: "Commit message"
        required: true
        type: string
        default: "Application promotion"

jobs:
  promote:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Copy container tag
        if: ${{ inputs.promote_container }}
        uses: canastro/copy-file-action@master
        with:
          source: "envs/${{ inputs.source_env }}/web-app/web-app.yaml"
          target: "envs/${{ inputs.target_env }}/web-app/web-app.yaml"
      - name: Copy settings
        if: ${{ inputs.promote_services }}
        uses: canastro/copy-file-action@master
        with:
          source: "envs/${{ inputs.source_env }}/web-app/web-app-svc.yaml"
          target: "envs/${{ inputs.target_env }}/web-app/web-app-svc.yaml"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.messsage }}
